ARG CONTAINER_VERSION=${CONTAINER_VERSION}
FROM sonarqube:${CONTAINER_VERSION}
ADD https://github.com/mc1arke/sonarqube-community-branch-plugin/releases/download/1.8.1/sonarqube-community-branch-plugin-1.8.1.jar /opt/sonarqube/extensions/plugins/
