ARG CONTAINER_VERSION=${CONTAINER_VERSION}
FROM mc1arke/sonarqube-with-community-branch-plugin:${CONTAINER_VERSION}
#FROM sonarqubecommunitybranch/sonarqube-with-community-branch-plugin:${CONTAINER_VERSION}