ARG CONTAINER_VERSION=${CONTAINER_VERSION}
FROM grafana/grafana:${CONTAINER_VERSION}

#USER root
#
#RUN apk --no-cache add telegraf
#COPY telegraf.conf /etc/telegraf/telegraf.conf
#CMD ["nohup telegraf --quiet &"]

USER grafana